#!/bin/bash
## Description: Produce unit test code coverage report.
## Usage: code-coverage
## Example: "ddev code-coverage"

readarray -t projects < <(awk -F',' '{ for( i=1; i<=NF; i++ ) print $i }' <<<"$PROJECT_NAMES")
delete=media
projects=( "${projects[@]/$delete}" )
delete=media_library
projects=( "${projects[@]/$delete}" )
## Enable the projects stored in the $PROJECT_NAMES environment variable.
for i in "${projects[@]}"
do
  ##/var/www/html/vendor/bin/phpunit -c /var/www/html/$DDEV_DOCROOT/modules/contrib/$i/phpunit.xml.dist --migrate-configuration
  XDEBUG_MODE=coverage /var/www/html/vendor/bin/phpunit -c /var/www/html/$DDEV_DOCROOT/modules/contrib/$i/phpunit.xml.dist --group=$i /var/www/html/$DDEV_DOCROOT/modules/contrib/$i --coverage-text
  ##--coverage-html /var/www/html/$DDEV_DOCROOT/coverage
done
