#!/bin/bash
## Description: Check for Drupal coding-standards violations using phpcs (run `ddev install` first)
## Usage: coding-standards
## Example: "ddev coding-standards"
readarray -t projects < <(awk -F',' '{ for( i=1; i<=NF; i++ ) print $i }' <<<"$PROJECT_NAMES")
delete=media
projects=( "${projects[@]/$delete}" )
delete=media_library
projects=( "${projects[@]/$delete}" )

## Enable the projects stored in the $PROJECT_NAMES environment variable.
for i in "${projects[@]}"
do
  /var/www/html/vendor/bin/phpcs -p $DDEV_DOCROOT/modules/contrib/$i
done
