#!/bin/bash
## Description: Fix coding-standards violations with phpcs (run `ddev install` first)
## Usage: coding-standards-fixes
## Example: "ddev coding-standards-fixes"
readarray -t projects < <(awk -F',' '{ for( i=1; i<=NF; i++ ) print $i }' <<<"$PROJECT_NAMES")
delete=media
projects=( "${projects[@]/$delete}" )
delete=media_library
projects=( "${projects[@]/$delete}" )
## Enable the projects stored in the $PROJECT_NAMES environment variable.
for i in "${projects[@]}"
do
  /var/www/html/vendor/bin/phpcbf -p $DDEV_DOCROOT/modules/contrib/$i
done
